### ISSUE TITLE
Quotation Marks in Echo are Not Trimmed

### ISSUE THREAD

**Issue by nallelcm** [a-trumier/eesh#10]
Description:
When using echo quotation marks are not properly removed.

Steps to Reproduce:
Enter an echo command with the text in quotes.
Example:  echo "hello world"

Expected Behaviour:
The system will remove the quotation marks
Bash example:
`nallelcm@vm-duck:~/test$ echo "hello world"`
`hello world`

Actual Behaviour:
The system does not trim the quotes
eesh example:
`$ echo "hello world"`
`"hello world"`

**Comment by a-trumier** [comment]
quotation marks (both double and single) added as per newest dev push. closing
