### ISSUE TITLE
Empty Strings return Error: Permission denied

### ISSUE THREAD

**Issue by nallelcm** [a-trumier/eesh#8]
Description:
When entering an empty string (or a series of spaces). The following error message is displayed: Error: Permission denied

Steps to Reproduce:
1. Press Enter

Expected Behaviour:
The prompt should be displayed again without an error message.

Actual Behaviour:
An error message is displayed before the prompt is provided.

**Comment by a-trumier** [comment]
one liner fix pushed to dev. closing
