### ISSUE TITLE
Whitespace is Not Properly Being Handled

### ISSUE THREAD

**Issue by nallelcm** [a-trumier/eesh#9]
Description:
Only space (' ') characters are being trimmed.  Other white spaces characters (e.g. Tab) are not being considered.

Steps to Reproduce:
Enter a command with whitespace that is not ' '

Expected Behaviour:
The system will properly trim the white space.
Bash example:
[home]# cd	test
[home/test]#

Actual Behaviour:
The system does not trim the white space.

**Comment by a-trumier** [comment]
whitespace issue completed as per newest dev push. closing
